import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
        <nav>
          <h1>Welcome to Next</h1>
          <ul>
            <li>
              <Link href="/">Home page</Link>
            </li>
            <li>
              <Link href="/ssr-streaming">Go to streaming</Link>
            </li>
            <li>
              <Link href="/ssr-blocking">Go to blocking SSR</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
